from enum import Enum

graphic_chars = {
    "ACUTE": "´",
    "AMPERSAND": "&",
    "APOSTROPHE": "’",
    "ASTERISK": "*",
    "BROKEN BAR": "¦",
    "CEDILLA": "¸",
    "CENT SIGN": "¢",
    "CIRCUMFLEX": "^",
    "COLON": ":",
    "COMMERCIAL AT": "@",
    "COPYRIGHT SIGN": "©",
    "CURRENCY SIGN": "¤",
    "DIERESIS": "¨",
    "DOLLAR SIGN": "$",
    "DOUBLE QUOTE": '"',
    "EQUALS SIGN": "=",
    "EXCLAMATION POINT": "!",
    "FEMININE ORDINAL INDICATOR": "ª",
    "GRAVE": "‘",
    "GREATER-THAN SIGN": ">",
    "HYPHEN MINUS SIGN SOFT HYPHEN": "-",
    "INVERTED EXCLAMATION MARK": "¡",
    "LEFT ANGLE QUOTATION MARK": "«",
    "LEFT PARENTHESIS": "(",
    "LEFT SQUARE BRACKET": "[",
    "LESS-THAN SIGN": "<",
    "LOW LINE UNDERSCORE": "_",
    "MACRON": "¯",
    "MASCULINE ORDINAL INDICATOR": "º",
    "MICRO": "μ",
    "MIDDLE DOT": "•",
    "NOT SIGN": "¬",
    "NUMBER SIGN": "#",
    "PERCENT SIGN": "%",
    "PERIOD FULL STOP": ".",
    "PILCROW": "¶",
    "PLUS SIGN": "+",
    "PLUS-MINUS SIGN": "±",
    "POUND SIGN": "£",
    "QUESTION MARK": "?",
    "REGISTERED TRADE MARK SIGN": "®",
    "REVERSE SOLIDUS": "\\",
    "RIGHT ANGLE QUOTATION MARK": "»",
    "RIGHT PARENTHESIS": ")",
    "RIGHT SQUARE BRACKET": "]",
    "RING ABOVE DEGREE SIGN": "°",
    "SECTION/PARAGRAPH SIGN": "§",
    "SEMICOLON": ";",
    "SOLIDUS": "/",
    "SUPERSCRIPT ONE": "1",
    "SUPERSCRIPT THREE": "3",
    "SUPERSCRIPT TWO": "2",
    "VULGAR FRACTION 1/4": "¼",
    "YEN SIGN": "¥",
}

GRAPHIC_CHARS = Enum("GRAPHIC_CHARS", graphic_chars)
